version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - 8002:80
        restart: always

    apache:
        image: httpd:latest
        ports:
            - 8001:80
        restart: always

    tomcat:
        image: tomcat:latest
        ports:
            - 8000:8080
        restart: always